- index.js
> Run autocannon twice to warm server

- benchmark-bench.js
- benchmark-compare.js
- benchmarks/total.js
- package.json
I think `total.js` should be included in this benchmark as well, especially for it being faster than a few of the other contenders.
> Total.js benchmark. 😎

- benchmark-compare.js
- benchmark.js
- benchmarks/express-route-prefix.js
- benchmarks/fastify.js
- benchmarks/koa-router.js
- benchmarks/koa.js
- benchmarks/micro-router.js
- benchmarks/micro.js
- benchmarks/restify.js
- benchmarks/take-five.js
- lib/bench.js
Made the use of `function()` over `arrow functions` consistent. Also added some missing `stricts`.
> Consistency using functions and 'strict'

- benchmark-bench.js
- benchmark-compare.js
- benchmarks/trek-engine-router.js
- benchmarks/trek-engine.js
- package.json
Maybe should update https://github.com/fastify/fastify#benchmarks.
> Trek Engine Benchmark

- package.json
Hi Fastify Team,
In `restify` `6.3.2` we made some performance optimization, could you please update our result here as well: https://www.fastify.io/benchmarks/
Thanks
> Update restify to 6.3.2

- benchmark-bench.js
> connection -> connections

- benchmark-bench.js
- benchmark-compare.js
- benchmarks/polka.js
- package.json
Maybe someone will need it, but these are not tests. It's just serving a plaintext on the main route.
#43 && lukeed/polka#3
> "polka" server benchmark

- benchmark-bench.js
- benchmarks/@leizm-web.js
- package.json
add `@leizm/web` to benchmarks
> add @leizm/web to benchmarks

- benchmark-bench.js
- benchmark-compare.js
- benchmarks/rayo.js
- package.json
- Added [rayo.js](https://github.com/GetRayo/rayo.js),
- fixed spelling mistakes,
- ordered options alphabetically
> feat: rayo.js. Spelling and options.

- benchmark-bench.js
- benchmarks/@leizm-web.js
- benchmarks/trek-engine-router.js
- benchmarks/trek-engine.js
This fixes `master` to pass `npm test`. I opened issue #57 to track getting a CI setup to prevent this going forward 👍
> Fix failues in npm test

- benchmarks/server-base-router.js
- benchmarks/server-base.js
- lib/packages.js
- package.json
This PR implements benchmarks for [server-base](https://github.com/JamesKyburz/server-base/tree/master/packages).
server-base is a small http server ideal for micro services (says the author=me with some bias :))
> server-base benchmarks

- benchmarks/egg.js
- package.json
> What is Egg?
Egg is born for building enterprise application and framework，we hope Egg will give birth to more application framework to help developers and developing team reduce development and maintenance costs.
Maintained by Alibaba employees.
website: https://eggjs.org/en/
> Add egg.js

- lib/packages.js
Sorry, I forget committed it in last pull request.
> Add egg.js to packages

- README.md
From https://github.com/fastify/benchmarks/issues/89#issuecomment-469773337
> Results with 40 second running time.

- benchmark-compare.js
Added the sort requests/sec DESC on the output of the md table, so the README updates will be ordered
> add sort on md table

- package.json
We should run the bench with fastify v3
> Update to fastify v3

- .github/workflows/benchmarks.yml
> Run bench on every commit on master

- benchmark-compare.js
> feat: add version in benchmarks

- benchmark-compare.js
> fix markdown table

- .github/workflows/benchmarks.yml
As titled
I followed [this documentation](https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#manually-running-a-workflow), it is shown the new button that will appear in the `Actions` tab
> add manual trigger on CI

- .github/dependabot.yml
- .github/workflows/ci.yml
https://github.com/fastify/benchmarks/issues/130 
Adding dependabot
> Adding dependabot

- benchmarks/koa-isomorphic-router.js
- lib/packages.js
- package.json
> Add koa-isomorphic-router

- benchmarks/koa-isomorphic-router.js
- package.json
> Update koa-isomorphic-router to v1.0.0

- benchmarks/take-five.js
> Fix take-five benchmark

- .github/dependabot.yml
- README.md
Finishes off migration to GitHub Actions
closes #129 and closes #130 
> ci(dependabot): update github actions

- .github/workflows/ci.yml
> Bump automerge action

- .github/workflows/metrics.yml
It fixes the commit process for metrics workflow.
> chore: fix metrics workflow

- benchmark-compare.js
- lib/packages.js
- package.json
> build(deps-dev): bump standard from 12.0.1 to 16.0.3

- package.json
> chore: revert chalk to v4

- benchmarks/fastify.js
Reverts fastify/benchmarks#223
> Revert "add IPv4 host"

- benchmarks/fastify.js
ref: #223 
**Do not merge it until https://github.com/fastify/fastify/pull/3606 is released**
> add IPv4 host

- benchmarks/h3-router.js
- lib/packages.js
Follow-up of #258 adding an h3-router benchmark.
> feat: add h3 with router

- benchmarks/istanbul.js
- lib/packages.js
- package.json
Added benchmark for IstanbulJS, a new NodeJS Framework
- Added `@istanbul/app` and `@istanbul/http` packages to `package.json`
- Added istanbul to `./lib/packages.js`
- Added `istanbul.js` to `./benchmarks/`
- #261 is fixed
> feat(#261): add benchmark for istanbuljs

- .github/workflows/benchmarks.yml
> workflow: use latest lts

- .github/workflows/ci.yml
> workflow: update nodejs version on ci

- benchmark-compare.js
- metrics/process-results.cjs
See https://github.com/fastify/fastify/pull/5057
> chore: optimize split param

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- .github/workflows/metrics.yml
Node 20 goes LTS today 🎉 
Seeing ~10% improvement on my local machine (M1 Pro) from node 18 > 20
> workflow: Upgrade Node to 20 (LTS)

- package.json
Add dependency to fix benchmark runs.  Closes https://github.com/fastify/benchmarks/issues/313.
> Add @tinyhttp/app to dependencies for benchmark

- package.json
Hi.
This PR includes updates to `hono` and `@hono/node-server`, which have been improved for better performance.
> bump up `hono` and `@hono/node-server`

- .github/workflows/ci.yml
Brings the workflow in line with our standard workflows.
> ci(ci): drop node 14-18; add node 22

- .github/dependabot.yml
> build(.github/dependabot): remove redundant ignore

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- .github/workflows/metrics.yml
Stops concurrent workflows from running, wasting time:
https://github.com/fastify/benchmarks/actions/workflows/benchmarks.yml
> ci: add concurrency groups

- .github/workflows/benchmarks.yml
- .github/workflows/ci.yml
- .github/workflows/metrics.yml
> ci: set job-level permissions, tidy style
