benchmarks/connect-router.js, benchmarks/connect.js, index.js, package.json
I hope it's OK, but figured I'd add the `connect` framework to the list here. 7.4k stars on GitHub and it's the low overhead version of Express.js for the most part. Users who don't need the Express.js sugar simply use `connect` (and + the `rotuer` if they want router -- can use other routers too, but most use the Express-like one).
=> Add connect framework

benchmarks/bare.js, benchmarks/connect-router.js, benchmarks/connect.js, benchmarks/express-route-prefix.js, benchmarks/express-with-middlewares.js, benchmarks/express.js, benchmarks/hapi.js, benchmarks/koa-router.js, benchmarks/koa.js, benchmarks/restify.js
This updates the various example such that the HTTP response from each server is as close as possible to each other. The target response is to be the same as the Fastify response of
```
$ curl -i http://127.0.0.1:3000/
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 17
Date: Sun, 10 Sep 2017 16:06:04 GMT
Connection: keep-alive
{"hello":"world"}
```
A couple frameworks will add `;charset=utf-8` to the content-type, which I just left like that. The Koa example wasn't even using the built-in JSON serialization of the framework and was sending with a content-type of text/plain, so this is fixed now. The only one I couldn't make the same was `take-five`, which provides no way to turn off the CORS feature, so there is still CORS response headers.
imo this is good enough to close …
=> Update examples to make all server responses the same

lib/autocannon.js
Sorry I didn't notice this issue with the previous PR #13 -- the `results` dir won't exist from a clean install, so it needs to be created if not already there.
=> Fix benchmark error on first install

benchmark-compare.js, lib/autocannon.js
I thought this could be cool with the existing compare command: to show the % diff that the autocannon-compare provides. I just added it to the existing faster than text. Looks like this:
```
$ benchmark compare
? What's your first pick? hapi
? What's your second one? fastify
Both are awesome but fastify is 505.63% faster than hapi
```
=> Show percentage difference in compare text

benchmarks/hapi.js, package.json
Some minor changes to the hapi script. Note that there is no need to declare the handler as `async` because that just adds a next tick for no reason. I turned off debugging which adds some listeners, as well as parsing of cookies. These don't make a noticeable difference but make it more obvious we are turning off functionality other frameworks don't all offer out of the box.
Last, I don't know the reason but the numbers I get seems to be best when running the test for at least 30 seconds. This is pretty consistent. Testing hapi and express:
5s:
- hapi 16,546
- express 17,266
20s:
- hapi 16803
- express 18324
30s:
- hapi 18257
- express 18608
45s:
- hapi 19010
- express 18282
For hapi, 45s seems to be consistently the best sample point.
=> Update hapi deps

benchmarks/restify.js
It shouldn't make any difference, but `name` is unnecessary here, it's an optional argument.
=> refactor(benchmarks): remove optional name form restify

benchmark-bench.js, benchmark-compare.js, benchmarks/spirit-router.js, benchmarks/spirit.js, package.json
Hello,
Nice benchmark project. Makes it easier for everyone to compare. I had a request to see how my project compared to fastify and added to it. (https://github.com/spirit-js/spirit/issues/19)
How can I get the results published to the table @ https://github.com/fastify/fastify ?
I know my project isn't as popular as express, fastify, koa, hapi, etc. But I think it definitely takes a different approach design wise and implementing compared to other projects and has some interesting results, so hopefully you guys are willing to include it.
=> add spirit to benchmarks

package.json
Both are awesome but fastify is 17.7% faster than restify
Both are awesome but restify is 44.63% faster than koa
Both are awesome but restify is 55.73% faster than express
Both are awesome but restify is 58.31% faster than hapi
• fastify request average is 33734.4
• restify request average is 28660.8
• koa request average is 19816
• express request average is 18404
• hapi request average is 18104
Can we update this page: https://www.fastify.io/benchmarks/ ? ;)
=> chore(restify): upgrade to 7.1.0

README.md, benchmark-compare.js
Hi! This is the first attempt to introuduce feature #62.
- Introduce `-p` argument
- Adds percentage value to the full comparsion table based on the fastest result with `benchmark compare -t -p`
- Also sorts table results based on `requests.mean` value. The sorting is hardoded.
=> Feature #62 add percentage value to cells

benchmarks/vapr.js, lib/packages.js, package.json
This adds a new HTTP framework called [vapr](https://github.com/JoshuaWise/vapr) to the list of benchmarked packages.
=> added vapr to the benchmarked packages

benchmark-compare.js
Nothing major, just adds a fixed decimal count to the performance metrics so that things line up nicely in the table.
=> Update the table to consistent decimal places for the metrics.

benchmarks/polkadot.js, lib/packages.js, package.json
Adds [`polkadot`](https://github.com/lukeed/polkadot) to the benchmark, which is most comparable to `micro`. I could add another candidate that pairs polkadot with a router (can use any), though not sure if there's much purpose to it nor how to label it 🙃 
Here are the results on my machine, hand-picking some items & using the standard autocannon settings
```
┌──────────┬────────┬────────────┬─────────┬───────────────┐
│          │ Router │ Requests/s │ Latency │ Throughput/Mb │
├──────────┼────────┼────────────┼─────────┼───────────────┤
│ bare     │ ✗      │ 58004.0    │ 1.66    │ 9.07          │
├──────────┼────────┼────────────┼─────────┼───────────────┤
│ fastify  │ ✓      │ 58606.4    │ 1.65    │ 9.17          │
├──────────┼────────┼────────────┼─────────┼───────────────┤
│ micro …
```
=> New: polkadot

benchmark-compare.js
`compare -tc` result outputs one extra `--:`, which breaks formatting:
```
|         | Router | Requests/s | Latency | Throughput/Mb |
| :--     | --:    | :-:        | --:     | --:           | --: |
| fastify | ✓      | 42029.9    | 2.27    | 6.57          |
| restify | ✓      | 29657.1    | 3.28    | 4.70          |
```
|         | Router | Requests/s | Latency | Throughput/Mb |
| :--     | --:    | :-:        | --:     | --:           | --: |
| fastify | ✓      | 42029.9    | 2.27    | 6.57          |
| restify | ✓      | 29657.1    | 3.28    | 4.70          |
Removing the extra `--:` makes the formatting work as expected:
```
|         | Router | Requests/s | Latency | Throughput/Mb |
| :--     | --:    | :-:        | --:     | --:           |
| fastify | ✓      | 42029.9    | 2.27 …
```
=> compare: fix Markdown table formatting

.gitignore
just putting back /results folder into .gitignore
see: https://github.com/fastify/benchmarks/pull/106#discussion_r373807047
=> Add: results folder into .gitignore

benchmarks/0http.js
The 0http framework added in #125 is not comparing apple-to-apples, as the HTTP response is different between the various frameworks. It is missing the `content-type` header.
---
I noticed this by looking at the README, as you can see
|                         | Version | Router | Requests/s | Latency | Throughput/Mb |
| :--                      | --:     | --:    | :-:        | --:     | --:           |
| 0http                    | 3.0.0   | ✓      | 63402.4    | 1.45    | 8.47          |
| fastify                  | 3.8.0   | ✓      | 61704.8    | 1.53    | 11.00         |
`0http` does more req/s at a _lower_ throughput, i.e. the content for each of those is smaller.
=> Set content-type for 0http

.github/workflows/benchmarks.yml, benchmark-compare.js
I was trying to test changes in #163 in my fork, it seemes `benchmark-compare` is stalled and not working and containes lots of duplicate logic. So I tried to rewrite and improve it. Also updated github action accordingly to use node LTS, new `compare -u` script to update readme and [github-actions-x/commit](https://github.com/github-actions-x/commit) to simplify commit and push step. Tried action and script in [my fork](https://github.com/pi0/benchmarks) with a subset of `benchmarks/`.
Note: Percentage flavor is removed since wasn't sure this PR and that feature is still wanted or not
=> chore: update benchmark-compare and github action

.github/workflows/benchmarks.yml
Currently, we are updating the benchmarks once per month, I think that for track purposes would be better run everyday
=> chore(benchmarks): update cron to run weekly

.github/dependabot.yml, package.json
`ora` in the latest major version (v6.x.x) was moved to pure ESM.
=> chore: revert ora to v5 non pure ESM

package.json
Reverts fastify/benchmarks#207
`chalk` now supports only ESM and it's breaking the benchmark action
=> Revert "chore(deps): bump chalk from 4.1.2 to 5.0.0"

benchmarks/fastify.js
After the https://github.com/fastify/fastify/pull/3606 will land in Fastify v4, there will be two HTTP servers spinning up on `localhost`.
So, the benchmark should start just one server tho
=> add IPv4 host

benchmark-bench.js
`select()` does not accept any args:
https://github.com/fastify/benchmarks/blob/master/benchmark-bench.js#L71
=> chore(benchmark-bench): remove superfluous arg

package.json
Reverts fastify/benchmarks#247 (It uses ESM only)
=> Revert "chore(deps): bump inquirer from 8.2.4 to 9.1.0"

benchmarks/fastify.js, benchmarks/trpc-router.js, lib/packages.js, package.json
I am adding an example of Fastify using [TRPC and its Fastify adapter](https://trpc.io/docs/v9/fastify) for defining API routes.
It's my first contribution, I am checking if I am missing anything for the PR.
=> Adds benchmark Fastify + TRPC router adapter

benchmarks/galatajs.js, lib/packages.js, package.json
I had a PR for the istanbuljs framework I developed yesterday and then got a feedback that the name istanbuljs was confusing. It was confusing when you think about it. I renamed the package name to galatajs. 
fixed #263
=> feat(#263): replace istanbuljs to galatajs

benchmarks/bare.cjs, benchmarks/h3-router.cjs, benchmarks/h3.cjs, benchmarks/server-base-router.cjs, benchmarks/spirit-router.cjs, benchmarks/spirit.cjs, benchmarks/vapr.cjs, benchmarks/yeps-router.cjs, benchmarks/yeps.cjs, metrics/process-results.cjs, metrics/startup-listen.cjs, metrics/startup-routes-schema.cjs, metrics/startup-routes.cjs, metrics/startup.cjs
See https://github.com/fastify/fastify-static/pull/407
=> perf: use `node:` prefix to bypass require.cache call for builtins

benchmarks/rayo.cjs, lib/packages.js, package.json
`Rayo` was removed here: https://github.com/fastify/benchmarks/commit/4ea026f2aa23db4cc644810d1f1643108a66cf2d
Not sure what the issue was then as `Rayo` is v.18 compatible. Adding it back in.
=> Rayo is back.

benchmarks/hapi.cjs, package.json
The test workflow still includes Node.js 14, but benchmarks are ran on Node.js 20
=> chore: remove make-promises-safe

benchmarks/micro-route.cjs, benchmarks/micro.cjs, benchmarks/microrouter.cjs
Micro semantics changed since major update (to version 10) and it seems to be not reflected in the benchmarks. I have fixed the syntax to make the benchmarks working again.
=> fix(micro): make micro benchmarks working

benchmarks/adonisjs.mjs, lib/packages.js, package.json
Hey there! 👋🏻 
This PR adds [AdonisJS](https://adonisjs.com/) Http server for benchmarking purpose.
I am not quite sure about some options in the `package.js` file, like the `extra` params.
AdonisJS comes by default with middleware enabled for example.
Let me know if I need to make any modification. 👍🏻
=> Add AdonisJS

benchmarks/adonisjs.mjs
Hey there! 👋🏻
I just noticed that the benchmark code for AdonisJS currently includes an `AsyncFunction` as the route handler, which isn't necessary in this context. Since there's no asynchronous operation within the handler, the `async` keyword is redundant and only introduces an unnecessary promise.
In this PR, I'm removing the `async` keyword to align the implementation more closely with other frameworks.
=> refactor(adonisjs): remove unneeded async function

benchmark-bench.js, benchmark-compare.js, benchmark.js, benchmarks/server-base-router.cjs, benchmarks/server-base.cjs, lib/autocannon.js, lib/bench.js, lib/packages.js, metrics/process-results.cjs, metrics/startup-listen.cjs, metrics/startup-routes-schema.cjs, metrics/startup-routes.cjs
- ESM is strict by default, so the `'use strict'` directive is not needed in .mjs files
- Added directive where it was missing in CommonJS files
=> fix: remove strict directive from mjs files, add missing to cjs files
